name: Deploy Documentation

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          cname: refn.chat
          force_orphan: true

  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEV_DEPLOY_KEY }}
          external_repository: millusdk/refn-chat-docs-dev
          publish_dir: .
          cname: develop.refn.chat
          force_orphan: true
